# Generated by Django 3.2.5 on 2022-02-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика'), ('Здоровье', 'Здоровье'), ('Культура', 'Культура')], default='Спорт', max_length=64),
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика'), ('Здоровье', 'Здоровье'), ('Культура', 'Культура')], default='Спорт', max_length=64),
        ),
    ]
