# Generated by Django 4.0.2 on 2022-02-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220207_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика'), ('Здоровье', 'Здоровье'), ('Культура', 'Культура')], default='Спорт', max_length=64),
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='news.PostCategory', to='news.Category'),
        ),
    ]
