# Generated by Django 4.0.2 on 2022-02-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика'), ('Здоровье', 'Здоровье'), ('Культура', 'Культура')], max_length=64),
        ),
    ]
