# Generated by Django 4.0.2 on 2022-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика'), ('Здоровье', 'Здоровье'), ('Культура', 'Культура')], default='Спорт', max_length=64),
        ),
    ]
