# Generated by Django 4.0.2 on 2022-02-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
