# Generated by Django 3.2.6 on 2021-08-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0002_auto_20210820_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('data', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
