# Generated by Django 3.2.6 on 2021-08-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='date',
        ),
    ]
